-- =====================================================================
-- PhishShield Bolivia — Esquema de base de datos
-- Motor: PostgreSQL 18
-- Nivel: intermedio (14 tablas, vistas, triggers, índices parciales)
-- =====================================================================
-- Bloques:
--   A. Organización y acceso ...... empresas, usuarios, sesiones
--   B. Inteligencia de amenazas ... entidades_suplantadas, dominios_lista
--   C. Motor de detección ......... modelos_ia, reglas_deteccion
--   D. Operación .................. analisis, analisis_indicadores,
--                                   alertas, feedback_analisis
--   E. Educación .................. lecciones, progreso_lecciones
--   F. Dashboard y trazabilidad ... reportes, auditoria
-- =====================================================================

SET client_encoding = 'UTF8';

-- ---------------------------------------------------------------------
-- Función reutilizable: mantiene actualizado_en al día automáticamente
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_set_actualizado_en()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.actualizado_en := NOW();
    RETURN NEW;
END;
$$;


-- =====================================================================
-- A. ORGANIZACIÓN Y ACCESO
-- =====================================================================

CREATE TABLE empresas (
    id_empresa      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_publico    UUID          NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    nombre          VARCHAR(150)  NOT NULL,
    nit             VARCHAR(20)   UNIQUE,
    sector          VARCHAR(60),
    ciudad          VARCHAR(60),
    plan            VARCHAR(20)   NOT NULL DEFAULT 'basico',
    activa          BOOLEAN       NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    actualizado_en  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_empresas_plan CHECK (plan IN ('basico', 'profesional', 'empresarial')),
    CONSTRAINT chk_empresas_nit  CHECK (nit IS NULL OR nit ~ '^[0-9]{7,15}$')
);

COMMENT ON TABLE  empresas IS 'Pymes u organizaciones suscritas a PhishShield.';
COMMENT ON COLUMN empresas.uuid_publico IS 'Identificador expuesto en la API; el BIGINT nunca sale al exterior.';

CREATE TRIGGER trg_empresas_actualizado
    BEFORE UPDATE ON empresas
    FOR EACH ROW EXECUTE FUNCTION fn_set_actualizado_en();


CREATE TABLE usuarios (
    id_usuario        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_publico      UUID         NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    id_empresa        BIGINT       REFERENCES empresas(id_empresa) ON DELETE SET NULL,
    nombres           VARCHAR(80)  NOT NULL,
    apellidos         VARCHAR(80),
    email             VARCHAR(150) NOT NULL,
    password_hash     VARCHAR(255) NOT NULL,
    rol               VARCHAR(20)  NOT NULL DEFAULT 'usuario',
    estado            VARCHAR(20)  NOT NULL DEFAULT 'activo',
    email_verificado  BOOLEAN      NOT NULL DEFAULT FALSE,
    intentos_fallidos SMALLINT     NOT NULL DEFAULT 0,
    ultimo_login      TIMESTAMPTZ,
    creado_en         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    actualizado_en    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_usuarios_rol      CHECK (rol IN ('admin', 'analista', 'empresa', 'usuario')),
    CONSTRAINT chk_usuarios_estado   CHECK (estado IN ('activo', 'inactivo', 'bloqueado', 'pendiente')),
    CONSTRAINT chk_usuarios_intentos CHECK (intentos_fallidos BETWEEN 0 AND 100),
    -- El email se guarda siempre en minúsculas: evita duplicados tipo Juan@x.com / juan@x.com
    CONSTRAINT chk_usuarios_email    CHECK (email = LOWER(email) AND email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);

CREATE UNIQUE INDEX uq_usuarios_email   ON usuarios(email);
CREATE        INDEX idx_usuarios_empresa ON usuarios(id_empresa) WHERE id_empresa IS NOT NULL;

CREATE TRIGGER trg_usuarios_actualizado
    BEFORE UPDATE ON usuarios
    FOR EACH ROW EXECUTE FUNCTION fn_set_actualizado_en();


-- Refresh tokens de JWT: permite cerrar sesión de un dispositivo puntual
CREATE TABLE sesiones (
    id_sesion          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario         BIGINT       NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    refresh_token_hash VARCHAR(255) NOT NULL UNIQUE,
    user_agent         VARCHAR(255),
    ip_origen          INET,
    expira_en          TIMESTAMPTZ  NOT NULL,
    revocada           BOOLEAN      NOT NULL DEFAULT FALSE,
    creado_en          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_sesiones_expira CHECK (expira_en > creado_en)
);

-- Índice parcial: solo interesan las sesiones vivas
CREATE INDEX idx_sesiones_activas ON sesiones(id_usuario) WHERE NOT revocada;


-- =====================================================================
-- B. INTELIGENCIA DE AMENAZAS (contexto boliviano)
-- =====================================================================

CREATE TABLE entidades_suplantadas (
    id_entidad      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(120) NOT NULL UNIQUE,
    tipo            VARCHAR(30)  NOT NULL,
    dominio_oficial VARCHAR(150),
    pais            CHAR(2)      NOT NULL DEFAULT 'BO',
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_entidades_tipo CHECK (
        tipo IN ('banco', 'billetera', 'gobierno', 'telco', 'ecommerce', 'educacion', 'otro'))
);

COMMENT ON TABLE entidades_suplantadas IS
    'Marcas bolivianas usadas como cebo en campañas de phishing. Es lo que diferencia a PhishShield de una herramienta genérica.';


CREATE TABLE dominios_lista (
    id_dominio  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dominio     VARCHAR(255) NOT NULL,
    lista       VARCHAR(10)  NOT NULL,
    id_entidad  BIGINT       REFERENCES entidades_suplantadas(id_entidad) ON DELETE SET NULL,
    fuente      VARCHAR(60)  NOT NULL DEFAULT 'manual',
    motivo      TEXT,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_dominios_lista  CHECK (lista IN ('blanca', 'negra', 'gris')),
    CONSTRAINT chk_dominios_minus  CHECK (dominio = LOWER(dominio)),
    CONSTRAINT uq_dominios_lista   UNIQUE (dominio, lista)
);

CREATE INDEX idx_dominios_activos ON dominios_lista(dominio) WHERE activo;


-- =====================================================================
-- C. MOTOR DE DETECCIÓN
-- =====================================================================

CREATE TABLE modelos_ia (
    id_modelo       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(80)  NOT NULL,
    version         VARCHAR(20)  NOT NULL,
    tipo            VARCHAR(20)  NOT NULL,
    algoritmo       VARCHAR(60),
    exactitud       NUMERIC(5,2),
    precision_val   NUMERIC(5,2),
    recall_val      NUMERIC(5,2),
    f1_val          NUMERIC(5,2),
    umbral_phishing NUMERIC(5,2) NOT NULL DEFAULT 70,
    activo          BOOLEAN      NOT NULL DEFAULT FALSE,
    entrenado_en    DATE,
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_modelos_tipo    CHECK (tipo IN ('url', 'texto', 'imagen', 'multimodal')),
    CONSTRAINT chk_modelos_umbral  CHECK (umbral_phishing BETWEEN 0 AND 100),
    CONSTRAINT chk_modelos_metricas CHECK (
        COALESCE(exactitud, 0)     BETWEEN 0 AND 100 AND
        COALESCE(precision_val, 0) BETWEEN 0 AND 100 AND
        COALESCE(recall_val, 0)    BETWEEN 0 AND 100 AND
        COALESCE(f1_val, 0)        BETWEEN 0 AND 100),
    CONSTRAINT uq_modelos_version  UNIQUE (nombre, version)
);

-- Regla de negocio en la BD: un solo modelo activo por tipo de análisis
CREATE UNIQUE INDEX uq_modelos_activo_por_tipo ON modelos_ia(tipo) WHERE activo;


CREATE TABLE reglas_deteccion (
    id_regla    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(40)  NOT NULL UNIQUE,
    descripcion VARCHAR(255) NOT NULL,
    categoria   VARCHAR(20)  NOT NULL,
    peso        NUMERIC(5,2) NOT NULL DEFAULT 1,
    activa      BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_reglas_categoria CHECK (
        categoria IN ('url', 'contenido', 'remitente', 'adjunto', 'visual')),
    CONSTRAINT chk_reglas_peso CHECK (peso BETWEEN 0 AND 100)
);

COMMENT ON TABLE reglas_deteccion IS
    'Heurísticas explicables que acompañan al modelo de IA (permiten decirle al usuario POR QUÉ algo es phishing).';


-- =====================================================================
-- D. OPERACIÓN
-- =====================================================================

CREATE TABLE analisis (
    id_analisis    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid_publico   UUID         NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    id_usuario     BIGINT       REFERENCES usuarios(id_usuario)  ON DELETE SET NULL,
    id_empresa     BIGINT       REFERENCES empresas(id_empresa)  ON DELETE SET NULL,
    id_modelo      BIGINT       REFERENCES modelos_ia(id_modelo) ON DELETE SET NULL,
    tipo           VARCHAR(20)  NOT NULL,
    origen         VARCHAR(20)  NOT NULL DEFAULT 'web',
    contenido      TEXT         NOT NULL,
    contenido_hash CHAR(64)     NOT NULL,
    dominio        VARCHAR(255),
    resultado      VARCHAR(20)  NOT NULL,
    nivel_riesgo   NUMERIC(5,2) NOT NULL DEFAULT 0,
    tiempo_ms      INTEGER,
    ip_origen      INET,
    fecha_analisis TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_analisis_tipo      CHECK (tipo IN ('url', 'correo', 'imagen')),
    CONSTRAINT chk_analisis_origen    CHECK (origen IN ('extension', 'plugin_correo', 'web', 'api')),
    CONSTRAINT chk_analisis_resultado CHECK (resultado IN ('seguro', 'sospechoso', 'phishing')),
    CONSTRAINT chk_analisis_riesgo    CHECK (nivel_riesgo BETWEEN 0 AND 100),
    CONSTRAINT chk_analisis_tiempo    CHECK (tiempo_ms IS NULL OR tiempo_ms >= 0),
    -- El veredicto y el puntaje no pueden contradecirse
    CONSTRAINT chk_analisis_coherencia CHECK (
        (resultado = 'seguro'     AND nivel_riesgo <  40) OR
        (resultado = 'sospechoso' AND nivel_riesgo >= 40 AND nivel_riesgo < 70) OR
        (resultado = 'phishing'   AND nivel_riesgo >= 70))
);

COMMENT ON COLUMN analisis.contenido_hash IS 'SHA-256 del contenido: permite deduplicar y cachear análisis repetidos.';

CREATE INDEX idx_analisis_usuario_fecha ON analisis(id_usuario, fecha_analisis DESC);
CREATE INDEX idx_analisis_empresa_fecha ON analisis(id_empresa, fecha_analisis DESC);
CREATE INDEX idx_analisis_resultado     ON analisis(resultado);
CREATE INDEX idx_analisis_hash          ON analisis(contenido_hash);
CREATE INDEX idx_analisis_dominio       ON analisis(dominio) WHERE dominio IS NOT NULL;


-- Tabla puente: qué reglas se dispararon en cada análisis y cuánto sumaron
CREATE TABLE analisis_indicadores (
    id_analisis BIGINT       NOT NULL REFERENCES analisis(id_analisis)          ON DELETE CASCADE,
    id_regla    BIGINT       NOT NULL REFERENCES reglas_deteccion(id_regla)     ON DELETE CASCADE,
    valor       VARCHAR(255),
    aporte      NUMERIC(5,2) NOT NULL DEFAULT 0,

    PRIMARY KEY (id_analisis, id_regla),
    CONSTRAINT chk_indicadores_aporte CHECK (aporte BETWEEN -100 AND 100)
);


CREATE TABLE alertas (
    id_alerta          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_analisis        BIGINT      NOT NULL UNIQUE REFERENCES analisis(id_analisis) ON DELETE CASCADE,
    severidad          VARCHAR(10) NOT NULL DEFAULT 'media',
    estado             VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    canal              VARCHAR(20) NOT NULL DEFAULT 'app',
    id_asignado_a      BIGINT      REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    notas              TEXT,
    fecha_notificacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_cierre       TIMESTAMPTZ,

    CONSTRAINT chk_alertas_severidad CHECK (severidad IN ('baja', 'media', 'alta', 'critica')),
    CONSTRAINT chk_alertas_estado    CHECK (estado IN ('pendiente', 'en_revision', 'revisada', 'descartada')),
    CONSTRAINT chk_alertas_canal     CHECK (canal IN ('app', 'email', 'extension', 'webhook')),
    CONSTRAINT chk_alertas_cierre    CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_notificacion)
);

CREATE INDEX idx_alertas_abiertas ON alertas(severidad, fecha_notificacion DESC)
    WHERE estado IN ('pendiente', 'en_revision');


-- Retroalimentación del usuario: insumo para reentrenar el modelo
CREATE TABLE feedback_analisis (
    id_feedback BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_analisis BIGINT      NOT NULL REFERENCES analisis(id_analisis) ON DELETE CASCADE,
    id_usuario  BIGINT      REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    veredicto   VARCHAR(20) NOT NULL,
    comentario  TEXT,
    creado_en   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_feedback_veredicto CHECK (
        veredicto IN ('correcto', 'falso_positivo', 'falso_negativo')),
    CONSTRAINT uq_feedback_usuario UNIQUE (id_analisis, id_usuario)
);


-- =====================================================================
-- E. EDUCACIÓN
-- =====================================================================

CREATE TABLE lecciones (
    id_leccion   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR(150) NOT NULL,
    descripcion  TEXT,
    nivel        VARCHAR(20)  NOT NULL DEFAULT 'basico',
    duracion_min SMALLINT,
    orden        SMALLINT     NOT NULL DEFAULT 1,
    publicada    BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_lecciones_nivel    CHECK (nivel IN ('basico', 'intermedio', 'avanzado')),
    CONSTRAINT chk_lecciones_duracion CHECK (duracion_min IS NULL OR duracion_min > 0)
);


CREATE TABLE progreso_lecciones (
    id_usuario    BIGINT      NOT NULL REFERENCES usuarios(id_usuario)  ON DELETE CASCADE,
    id_leccion    BIGINT      NOT NULL REFERENCES lecciones(id_leccion) ON DELETE CASCADE,
    estado        VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    puntaje       SMALLINT,
    completado_en TIMESTAMPTZ,

    PRIMARY KEY (id_usuario, id_leccion),
    CONSTRAINT chk_progreso_estado  CHECK (estado IN ('pendiente', 'en_curso', 'completada')),
    CONSTRAINT chk_progreso_puntaje CHECK (puntaje IS NULL OR puntaje BETWEEN 0 AND 100),
    CONSTRAINT chk_progreso_cierre  CHECK (
        (estado = 'completada' AND completado_en IS NOT NULL) OR
        (estado <> 'completada' AND completado_en IS NULL))
);


-- =====================================================================
-- F. DASHBOARD Y TRAZABILIDAD
-- =====================================================================

CREATE TABLE reportes (
    id_reporte       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa       BIGINT      NOT NULL REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    periodo_inicio   DATE        NOT NULL,
    periodo_fin      DATE        NOT NULL,
    total_analisis   INTEGER     NOT NULL DEFAULT 0,
    total_phishing   INTEGER     NOT NULL DEFAULT 0,
    total_alertas    INTEGER     NOT NULL DEFAULT 0,
    generado_por     BIGINT      REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    fecha_generacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_reportes_periodo   CHECK (periodo_fin >= periodo_inicio),
    CONSTRAINT chk_reportes_totales   CHECK (
        total_analisis >= 0 AND total_alertas >= 0 AND
        total_phishing BETWEEN 0 AND total_analisis),
    CONSTRAINT uq_reportes_periodo    UNIQUE (id_empresa, periodo_inicio, periodo_fin)
);


CREATE TABLE auditoria (
    id_evento           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          BIGINT      REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
    accion              VARCHAR(60) NOT NULL,
    entidad             VARCHAR(60),
    id_entidad_afectada BIGINT,
    detalle             JSONB,
    ip_origen           INET,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_auditoria_fecha   ON auditoria(creado_en DESC);
CREATE INDEX idx_auditoria_detalle ON auditoria USING GIN (detalle);


-- =====================================================================
-- VISTAS PARA EL DASHBOARD
-- =====================================================================

-- Resumen por empresa: lo que consume la pantalla principal del dashboard
CREATE OR REPLACE VIEW v_resumen_empresa AS
SELECT
    e.id_empresa,
    e.nombre                                                        AS empresa,
    COUNT(a.id_analisis)                                            AS total_analisis,
    COUNT(*) FILTER (WHERE a.resultado = 'phishing')                AS total_phishing,
    COUNT(*) FILTER (WHERE a.resultado = 'sospechoso')              AS total_sospechosos,
    ROUND(AVG(a.nivel_riesgo), 2)                                   AS riesgo_promedio,
    MAX(a.fecha_analisis)                                           AS ultimo_analisis
FROM empresas e
LEFT JOIN analisis a ON a.id_empresa = e.id_empresa
GROUP BY e.id_empresa, e.nombre;


-- Bandeja de alertas abiertas con su contexto
CREATE OR REPLACE VIEW v_alertas_abiertas AS
SELECT
    al.id_alerta,
    al.severidad,
    al.estado,
    an.tipo,
    an.contenido,
    an.nivel_riesgo,
    u.email        AS usuario_afectado,
    e.nombre       AS empresa,
    al.fecha_notificacion
FROM alertas al
JOIN analisis an ON an.id_analisis = al.id_analisis
LEFT JOIN usuarios u ON u.id_usuario = an.id_usuario
LEFT JOIN empresas e ON e.id_empresa = an.id_empresa
WHERE al.estado IN ('pendiente', 'en_revision');


-- Dominios más reportados como maliciosos
CREATE OR REPLACE VIEW v_top_dominios_maliciosos AS
SELECT
    dominio,
    COUNT(*)                      AS veces_detectado,
    ROUND(AVG(nivel_riesgo), 2)   AS riesgo_promedio,
    MAX(fecha_analisis)           AS ultima_deteccion
FROM analisis
WHERE resultado = 'phishing' AND dominio IS NOT NULL
GROUP BY dominio
ORDER BY veces_detectado DESC;
